#!/bin/bash

# ===== Vim =====
v() {
    command vim "$@"
    cd .
}

# ===== React =====
ro() {
    cd "$ROOT/app/routes" >/dev/null 2>&1 || \
    cd "$ROOT/src/routes" >/dev/null 2>&1 || \
    {
        echo "Expected one of the following folders:
    => src/routes | app/routes" >&2
    }
}

co(){
    cd "$ROOT/src/components" >/dev/null 2>&1 || \
    cd "$ROOT/app/components" >/dev/null 2>&1 || \
    {
        echo "Expected one of the following folders:
    => src/components | app/components" >&2
        return 1
    }
}

s() {
    cd "$ROOT/src" >/dev/null 2>&1 || \
    cd "$ROOT/app" >/dev/null 2>&1 || \
        echo "Expected one of the following folders:
    => src | app" >&2
        return 1
}


# ===== Git =====
git() {
    case "$1" in
        switch|checkout|commit)
            command git "$@" && cd "$PWD"
            ;;
        branch)
            command git "$@" | cat
            ;;
        *)
            command git "$@"
            ;;
    esac
}

# ===== Miss =====
yy() {
  wl-copy "c $PWD"
}
